name: '🚀Unit Testing'

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install flake8 pylint

      - name: Perform Code Linting with flake8
        run: |
          flake8 .

      - name: Perform Code Linting with pylint
        run: |
          pylint $(git ls-files '*.py')

  unittest-ubuntu:
    strategy:
      matrix:
        python-version: [ "3.9", "3.10" ]
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-mock pytest-cov requests-mock

      - name: Run Unit Tests with pytest
        run: |
          pytest

  unittest-macos:
    strategy:
      matrix:
        python-version: [ "3.9", "3.10" ]
    runs-on: macos-latest
    needs: linting
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-mock pytest-cov requests-mock

      - name: Run Unit Tests with pytest
        run: |
          pytest

  unittest-windows:
    strategy:
      matrix:
        python-version: [ "3.9", "3.10" ]
    runs-on: windows-latest
    needs: linting
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if (Test-Path -Path .\requirements.txt) { pip install -r .\requirements.txt }
          pip install pytest pytest-mock pytest-cov requests-mock

      - name: Run Unit Tests with pytest
        run: |
          pytest

  code-coverage:
    runs-on: ubuntu-latest
    needs:
      - unittest-ubuntu
      - unittest-macos
      - unittest-windows
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-mock pytest-cov requests-mock

      - name: Run code coverage with pytest-cov
        run: |
          pytest --cov-config=setup.cfg --cov=src --cov-report=xml --cov-report=term-missing

      - name: Upload Coverage Report to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
